name: Tests

on: push:
    branches:
      - master

jobs:
  report-test-coverage:
    name: Report test coverage on push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 16

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Run tests and generate coverage report
        run: pnpm test
        timeout-minutes: 5

      - name: Upload coverage for Web package
        if: success()
        uses: codecov/codecov-action@v3
        timeout-minutes: 5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: packages/web/coverage/coverage-final.json
          flags: web

      - name: Upload coverage for Mobile package
        if: success()
        uses: codecov/codecov-action@v3
        timeout-minutes: 5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: packages/mobile/coverage/coverage-final.json
          flags: mobile
